(() => {
  const esc=s=>window.escapeHTML(s);let tabCount=0;const pdfs=new Map();
  window.createTabs=(tabs,render)=>{const id='tabs-'+tabCount++,section=document.createElement('section');section.className='tabs-block';section.innerHTML=`<div class="tab-scroll"><div class="tab-list" role="tablist" aria-label="${esc(tabs.map(t=>t.label).join(', '))}">${tabs.map((t,i)=>`<button id="${id}-${i}" role="tab" aria-selected="${i===0}" tabindex="${i===0?0:-1}" aria-controls="${id}-panel">${esc(t.label)}</button>`).join('')}</div></div><div class="tab-panel" id="${id}-panel" role="tabpanel" aria-labelledby="${id}-0" tabindex="0"></div>`;const buttons=[...section.querySelectorAll('[role=tab]')],panel=section.querySelector('[role=tabpanel]');let current=-1;
    function select(i,focus=false){if(i===current)return;current=i;panel.querySelectorAll('[data-ready],.deck').forEach(n=>n.dispose?.());buttons.forEach((b,j)=>{b.setAttribute('aria-selected',String(i===j));b.tabIndex=i===j?0:-1;});panel.setAttribute('aria-labelledby',buttons[i].id);panel.innerHTML='';const content=render(tabs[i]);if(typeof content==='string')panel.innerHTML=content;else if(content)panel.append(content);window.initCharts?.(panel);window.initDecks?.(panel);window.fixCitations?.(panel);if(focus){buttons[i].focus();buttons[i].scrollIntoView({block:'nearest',inline:'nearest',behavior:'smooth'});}}
    buttons.forEach((b,i)=>{b.addEventListener('click',()=>select(i));b.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=(i+1)%tabs.length;else if(e.key==='ArrowLeft')n=(i-1+tabs.length)%tabs.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=tabs.length-1;if(n!==undefined){e.preventDefault();select(n,true);}});});select(0);return section;
  };
  window.mediaHTML=m=>{if(!m)return '';const src=m.src||m.url||'',type=m.type||(src.includes('vimeo.com')?'vimeo':/\.pdf(?:\?|$)/i.test(src)?'pdf':/\.mp4(?:\?|$)/i.test(src)?'video':'image');if(type==='vimeo'||type==='iframe'||type==='game'){let url=src;if(type==='vimeo'){url=src.replace('https://vimeo.com/','https://player.vimeo.com/video/');url+=(url.includes('?')?'&':'?')+'title=0&byline=0&portrait=0';}return `<div class="media-wrap"><iframe title="${esc(m.title||'Interactive demonstration')}" src="${esc(url)}" loading="lazy" allow="autoplay; fullscreen; picture-in-picture; gamepad" allowfullscreen></iframe></div>`;}
    if(type==='video')return `<div class="media-wrap"><video src="${esc(src)}" ${m.poster?`poster="${esc(m.poster)}"`:''} controls playsinline loop preload="metadata" aria-label="${esc(m.title||'Demonstration video')}"></video></div>`;
    if(type==='pdf')return `<div class="deck" data-pdf="${esc(src)}" data-title="${esc(m.title||'Slide deck')}"><div class="pdf-page"><canvas aria-label="${esc(m.title||'Document page')}"></canvas></div><div class="deck-controls"><span class="count">Loading document…</span><button data-page="prev" aria-label="Previous slide" disabled>←</button><button data-page="next" aria-label="Next slide" disabled>→</button><button data-fullscreen aria-label="Enter fullscreen">⛶</button><a href="${esc(m.original||src)}" target="_blank" rel="noopener" aria-label="Open original document">↗</a></div></div>`;
    return `<button class="image-button" data-zoom="${esc(src)}" aria-label="Expand ${esc(m.title||'image')}"><img src="${esc(src)}" alt="${esc(m.title||'Demonstration')}" loading="lazy" style="width:100%;display:block;border-radius:6px"></button>`;
  };
  const observedDecks=new WeakSet();let pdfModule;
  async function renderDeck(el){if(el.dataset.ready)return;el.dataset.ready='true';let documentPdf,page=1,renderTask,busy=false,dirty=false,disposed=false;const canvas=el.querySelector('canvas'),previous=el.querySelector('[data-page=prev]'),next=el.querySelector('[data-page=next]'),count=el.querySelector('.count');let module;try{module=await(pdfModule||(pdfModule=import('./assets/pdf.min.mjs')));module.GlobalWorkerOptions.workerSrc='./assets/pdf.worker.min.mjs';if(!pdfs.has(el.dataset.pdf))pdfs.set(el.dataset.pdf,module.getDocument({url:el.dataset.pdf,disableAutoFetch:true}).promise);documentPdf=await pdfs.get(el.dataset.pdf);}catch(e){count.innerHTML='Document preview unavailable. Use ↗ to open it.';console.error(e);return;}
    async function draw(){if(disposed)return;if(busy){dirty=true;return;}busy=true;try{const pdfPage=await documentPdf.getPage(page);const base=pdfPage.getViewport({scale:1});const width=Math.max(150,el.clientWidth);const viewport=pdfPage.getViewport({scale:width/base.width*Math.min(2,devicePixelRatio)});canvas.width=viewport.width;canvas.height=viewport.height;canvas.style.width='100%';canvas.style.height='auto';renderTask=pdfPage.render({canvasContext:canvas.getContext('2d'),viewport});await renderTask.promise;count.textContent=page+' / '+documentPdf.numPages;previous.disabled=page===1;next.disabled=page===documentPdf.numPages;}catch(e){if(e.name!=='RenderingCancelledException')console.error(e);}finally{busy=false;if(dirty){dirty=false;draw();}}}
    const turn=n=>{page=Math.max(1,Math.min(documentPdf.numPages,page+n));draw();};previous.addEventListener('click',()=>turn(-1));next.addEventListener('click',()=>turn(1));el.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();turn(e.key==='ArrowLeft'?-1:1);}});el.querySelector('[data-fullscreen]').addEventListener('click',()=>{if(document.fullscreenElement===el)document.exitFullscreen();else el.requestFullscreen?.();});el.tabIndex=0;let resizeTimer;const ro=new ResizeObserver(()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(draw,150);});ro.observe(el);el.dispose=()=>{disposed=true;ro.disconnect();clearTimeout(resizeTimer);renderTask?.cancel();};await draw();
  }
  const deckObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){renderDeck(e.target);deckObserver.unobserve(e.target);}}),{rootMargin:'500px'});
  window.initDecks=root=>(root||document).querySelectorAll('.deck').forEach(el=>{if(!observedDecks.has(el)){observedDecks.add(el);deckObserver.observe(el);}});
})();
