(() => {
  const palette={theme1:'#294e82',theme2_blue:'#4d7ab8',theme5_blue:'#e8f3fe',theme3_blue:'#7daaf2',theme3_orange:'#a36d4a',theme4_orange:'#875333',theme5_orange:'#64341f',theme2_green:'#428478',theme4_green:'#73a898',theme5_green:'#94bfa5',theme3_purple:'#b296da'};
  const colorFor=m=>/Astra/.test(m)?palette.theme3_blue:/Sol/.test(m)?palette.theme1:/Fable 5.1/.test(m)?palette.theme3_orange:/Fable/.test(m)?palette.theme4_orange:/Opus/.test(m)?palette.theme5_orange:palette.theme4_green;
  const esc=s=>window.escapeHTML(s);let sourcePromise=fetch('./chart-data.json').then(r=>{if(!r.ok)throw Error('Chart data unavailable');return r.json();});
  function normalise(obj){if(Array.isArray(obj))return obj.map(normalise);if(obj&&typeof obj==='object'){const o={};for(const [k,v]of Object.entries(obj))o[k]=normalise(v);return o;}return typeof obj==='string' ? (palette[obj] || obj.replaceAll('$$','$')) : obj;}
  const displayName=m=>String(m==='astra'?'GPT-6 Astra':m==='gpt-5.6-sol'?'GPT-5.6 Sol':m||'').replace(/\s+[·(].*$/,'');
  function prepare(record,width){const s=normalise(record.vegaLiteSpec);delete s.title;s.width=Math.max(180,width-64);s.height=Math.max(260,width*.63);s.background='transparent';s.padding={left:8,right:12,top:10,bottom:10};s.autosize={type:'fit',contains:'padding',resize:true};s.params=[...(s.params||[]),{name:'dotcomChartWidth',value:width},{name:'highlightModel',value:''}];
    function data(rows){if(!Array.isArray(rows))return;rows.forEach(d=>{const m=d.model_display||d.modelLabel||d.model||d.modelId||d.label;d.chart_legend_model=displayName(d.chart_legend_model||m);d.chart_dom_model=d.chart_dom_model||m;d.chart_dom_report_status=d.chart_dom_report_status||'__measured_data__';});}data(s.data?.values);Object.values(s.datasets||{}).forEach(data);
    function visit(o){if(!o||typeof o!=='object')return;data(o.data?.values);Object.values(o.datasets||{}).forEach(data);if(o.encoding){for(const v of Object.values(o.encoding)){if(v&&typeof v==='object'&&'legend'in v)v.legend=null;}if(o.mark){o.encoding.opacity={condition:{test:"highlightModel === '' || replace(datum.chart_legend_model || datum.chart_dom_model || datum.model_display || datum.modelLabel || datum.model || '', /\\s+[·(].*$/, '') === highlightModel",value:1},value:.14};}}if(o.layer)o.layer.forEach(visit);}visit(s);
    s.config={...(s.config||{}),font:'OpenAI, Arial',background:'transparent',view:{stroke:null},axis:{labelColor:'#c5c9ce',titleColor:'#c5c9ce',domainColor:'#92989f',tickColor:'#92989f',grid:false,labelFontSize:12,titleFontSize:12,titleFontWeight:400,titlePadding:15,labelPadding:8,labelLimit:140},legend:{disable:true},text:{color:'#e6e8eb',fontSize:12},bar:{size:75},line:{strokeWidth:2}};return s;}
  function sourceRows(record){const rows=[];function walk(o){if(!o||typeof o!=='object')return;if(Array.isArray(o)){o.forEach(walk);return;}if(o.data?.values)rows.push(...o.data.values);for(const r of Object.values(o.datasets||{}))if(Array.isArray(r))rows.push(...r);for(const [k,v]of Object.entries(o))if(k!=='data'&&k!=='datasets')walk(v);}walk(record.vegaLiteSpec);return rows;}
  function modelNames(record){const names=sourceRows(record).map(d=>d.chart_legend_model||d.model_display||d.modelLabel||d.model||d.modelId).filter(Boolean);function walk(o){if(!o||typeof o!=='object')return;if(Array.isArray(o)){o.forEach(walk);return;}if(o.field&&/model/i.test(o.field)&&Array.isArray(o.scale?.domain))names.push(...o.scale.domain.filter(d=>typeof d==='string'&&/^(GPT|Claude|Gemini|Fable|Opus)/.test(d)));Object.values(o).forEach(walk);}walk(record.vegaLiteSpec);return [...new Set(names.map(displayName))].sort((a,b)=>{const n=x=>/Astra/.test(x)?0:/Sol/.test(x)?1:/Fable 5.1/.test(x)?2:/Fable/.test(x)?3:/Opus/.test(x)?4:5;return n(a)-n(b);});}
  function save(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
  const tip=document.getElementById('tooltip');
  function tooltip(handler,event,item,value){if(!value){tip.hidden=true;return;}tip.innerHTML=Object.entries(value).map(([k,v])=>`<div>${esc(k)}: <strong>${esc(v)}</strong></div>`).join('');tip.hidden=false;tip.style.left=Math.max(8,Math.min(innerWidth-270,event.clientX+14))+'px';tip.style.top=Math.max(8,Math.min(innerHeight-tip.offsetHeight-8,event.clientY+14))+'px';}
  async function createChart(el){if(el.dataset.ready)return;el.dataset.ready='true';const records=await sourcePromise;let record=records[Number(el.dataset.chart)];if(!record)return;const title=el.dataset.title||(typeof record.vegaLiteSpec.title==='string'?record.vegaLiteSpec.title:record.vegaLiteSpec.title?.text)||'Benchmark';const models=modelNames(record);let view=null,highlight='',disposed=false;const filters=record.dotcomConfig.filters||[];
    el.innerHTML=`<div class="chart-card"><div class="chart-header"><h3 class="chart-title">${esc(title)}</h3><button class="icon-button download-menu" aria-label="Chart options for ${esc(title)}" aria-expanded="false"><svg viewBox="0 0 24 24"><path d="M12 3v12m-5-5 5 5 5-5M4 15v4a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-4"/></svg></button></div><div class="chart-options" hidden><button data-action="png">Download PNG</button><button data-action="svg">Download SVG</button><button data-action="copy">Copy link</button></div>${filters.map(f=>`<select class="chart-select" aria-label="${esc(title)} dataset" data-signal="${f.parameterName}">${f.options.map(o=>`<option value="${esc(o.value)}" ${o.value===f.defaultValue?'selected':''}>${esc(o.label)}</option>`).join('')}</select>`).join('')}<div class="legend" aria-label="Chart legend">${models.map(m=>`<button aria-pressed="true" data-model="${esc(m)}" aria-label="Highlight ${esc(m)}"><b style="color:${colorFor(m)}">${/Astra/.test(m)?'★':/Sol/.test(m)?'●':/Fable 5.1/.test(m)?'■':/Fable/.test(m)?'◆':'▲'}</b>${esc(m)}</button>`).join('')}</div><div class="vega-plot" role="img" aria-label="${esc(title)} benchmark chart"></div></div>`;
    const card=el.querySelector('.chart-card'),plot=el.querySelector('.vega-plot'),menu=el.querySelector('.chart-options'),toggle=el.querySelector('.download-menu');
    async function render(){if(disposed)return;view?.finalize();try{const spec=prepare(record,card.clientWidth-40);for(const select of el.querySelectorAll('select')){const p=spec.params.find(p=>p.name===select.dataset.signal);if(p)p.value=select.value;}const runtime=vega.parse(vegaLite.compile(spec).spec);view=new vega.View(runtime,{renderer:'svg',container:plot,hover:true,tooltip}).initialize();await view.runAsync();if(highlight)await view.signal('highlightModel',highlight).runAsync();plot.querySelector('svg')?.setAttribute('width','100%');}catch(error){console.error('Chart rendering failed:',title,error);plot.innerHTML='<p class="data-note">The chart could not load. <a href="https://openai.com/index/gpt-6-astra/" target="_blank" rel="noopener">View the original benchmark</a>.</p>';}}
    el.querySelectorAll('select').forEach(s=>{const size=()=>s.style.width=(s.selectedOptions[0].text.length*7+38)+'px';size();s.addEventListener('change',()=>{size();tip.hidden=true;try{view.signal(s.dataset.signal,s.value).runAsync();}catch{render();}});});
    el.querySelectorAll('[data-model]').forEach(b=>b.addEventListener('click',()=>{highlight=highlight===b.dataset.model?'':b.dataset.model;el.querySelectorAll('[data-model]').forEach(n=>n.setAttribute('aria-pressed',String(!highlight||n.dataset.model===highlight)));view?.signal('highlightModel',highlight).runAsync();}));
    toggle.addEventListener('click',()=>{menu.hidden=!menu.hidden;toggle.setAttribute('aria-expanded',String(!menu.hidden));});
    menu.addEventListener('click',async e=>{const action=e.target.dataset.action;if(!action)return;menu.hidden=true;toggle.setAttribute('aria-expanded','false');if(action==='copy'){const panel=el.closest('[role="tabpanel"]');const anchor=panel?.getAttribute('aria-labelledby')||'benchmark-'+el.dataset.chart;if(!panel)el.id=anchor;try{await navigator.clipboard.writeText(location.origin+location.pathname+'#'+anchor);e.target.textContent='Link copied';setTimeout(()=>e.target.textContent='Copy link',1600);}catch{e.target.textContent='Could not copy link';}}else if(view){try{if(action==='svg')save(new Blob([await view.toSVG()],{type:'image/svg+xml'}),title+'.svg');else{const url=await view.toImageURL('png',2),a=document.createElement('a');a.href=url;a.download=title+'.png';a.click();}}catch(error){console.error(error);}}});
    let oldWidth=0,timer;const ro=new ResizeObserver(entries=>{const width=Math.round(entries[0].contentRect.width);if(Math.abs(width-oldWidth)<4)return;oldWidth=width;clearTimeout(timer);timer=setTimeout(render,80);});ro.observe(card);el.dispose=()=>{disposed=true;ro.disconnect();clearTimeout(timer);view?.finalize();};await render();
  }
  const io=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){createChart(e.target);io.unobserve(e.target);}},{rootMargin:'400px'});
  window.initCharts=root=>(root||document).querySelectorAll('[data-chart]:not([data-ready])').forEach(el=>io.observe(el));
  window.renderChart=createChart;
})();
