(() => {
  'use strict';
  const header=document.querySelector('.header'),menu=document.getElementById('mega-menu'),backdrop=document.querySelector('.menu-backdrop');
  const links={Research:[['Research','Research Index|https://openai.com/research/index/','Research Overview|https://openai.com/research/','Economic Research|https://openai.com/signals/'],['Latest Advancements','GPT-6 Astra|#introduction','GPT-5.6|https://openai.com/index/gpt-5-6/','GPT-5.5|https://openai.com/index/introducing-gpt-5-5/','GPT-5.4|https://openai.com/index/introducing-gpt-5-4/'],['Safety','Safety Approach|https://openai.com/safety/','Deployment Safety|https://deploymentsafety.openai.com/','Security & Privacy|https://openai.com/security-and-privacy/']],Products:[['Products','ChatGPT|https://chatgpt.com/','Codex|https://openai.com/codex/','API Platform|https://openai.com/api/'],['ChatGPT','For Business|https://chatgpt.com/business/','For Enterprise|https://chatgpt.com/business/enterprise/','For Education|https://chatgpt.com/business/education/'],['Explore','Release Notes|https://openai.com/products/release-notes/','Download ChatGPT|https://chatgpt.com/download/']],Business:[['Business','Overview|https://openai.com/business/','Solutions|https://openai.com/solutions/','Resources|https://openai.com/business/learn/'],['Get started','Customer Stories|https://openai.com/business/stories/','Contact Sales|https://openai.com/contact-sales/']],Developers:[['Developers','API Platform|https://openai.com/api/','Documentation|https://developers.openai.com/api/docs','Resources|https://developers.openai.com/'],['Build','Apps SDK|https://developers.openai.com/apps-sdk/','Open Models|https://openai.com/open-models/','Developer Forum|https://community.openai.com/']],Company:[['Company','About Us|https://openai.com/about/','Our Charter|https://openai.com/charter/','Careers|https://openai.com/careers/','News|https://openai.com/news/']], 'Log in':[['Log in','ChatGPT ↗|https://chatgpt.com/auth/login','API Platform ↗|https://platform.openai.com/login','Sora ↗|https://sora.com/']]};
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));window.escapeHTML=esc;
  const linkHTML=s=>{const [label,url]=s.split('|');return `<a href="${esc(url)}" ${url.startsWith('#')?'':'target="_blank" rel="noopener"'}>${esc(label)}</a>`;};
  let currentMenu=null;function closeMenu(){menu.hidden=backdrop.hidden=true;header.classList.remove('menu-open');document.querySelectorAll('[data-menu]').forEach(b=>b.setAttribute('aria-expanded','false'));document.querySelector('.mobile-menu').setAttribute('aria-expanded','false');currentMenu=null;}
  function showMenu(name){if(currentMenu===name)return closeMenu();currentMenu=name;const groups=links[name]||Object.entries(links).map(([k,v])=>[k,...v[0].slice(1)]);menu.innerHTML=`${name==='All'?'<button class="mobile-search-row" data-mobile-search>Search <span>⌕</span></button>':''}<div class="mega-grid">${groups.map(g=>`<div><h2>${esc(g[0])}</h2>${g.slice(1).map(linkHTML).join('')}</div>`).join('')}</div>`;menu.hidden=backdrop.hidden=false;header.classList.add('menu-open');document.querySelectorAll('[data-menu]').forEach(b=>b.setAttribute('aria-expanded',String(b.dataset.menu===name)));}
  document.querySelectorAll('[data-menu]').forEach(b=>{b.setAttribute('aria-expanded','false');b.addEventListener('click',()=>showMenu(b.dataset.menu));});document.querySelector('.mobile-menu').addEventListener('click',()=>{showMenu('All');document.querySelector('.mobile-menu').setAttribute('aria-expanded',String(!menu.hidden));});backdrop.addEventListener('click',closeMenu);menu.addEventListener('click',e=>{if(e.target.closest('[data-mobile-search]')){closeMenu();search.showModal();input.focus();}if(e.target.closest('a'))closeMenu();});addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>30),{passive:true});
  const search=document.getElementById('search-dialog'),input=document.getElementById('search-input'),results=document.getElementById('search-results');document.querySelectorAll('.search-trigger').forEach(b=>b.addEventListener('click',()=>{closeMenu();search.showModal();input.focus();}));document.querySelectorAll('.close-dialog').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
  let searchId=0;
  function doSearch(){const q=input.value.trim().toLowerCase();if(!q){results.innerHTML='<p>Find a section, benchmark, or demonstration.</p>';return;}const items=[...document.querySelectorAll('main h2,main h3,main [role="tab"],main .prose p')].filter(e=>e.textContent.toLowerCase().includes(q));results.innerHTML=items.slice(0,12).map((e,i)=>{if(!e.id)e.id='search-result-'+searchId++;return `<a href="#${e.id}">${esc(e.textContent.slice(0,150))}${e.textContent.length>150?'…':''}</a>`;}).join('')||'<p>No matches on this page.</p>';}
  input.addEventListener('input',doSearch);document.getElementById('search-form').addEventListener('submit',e=>{e.preventDefault();doSearch();});results.addEventListener('click',e=>{const a=e.target.closest('a');if(a){const el=document.querySelector(a.getAttribute('href'));search.close();if(el?.getAttribute('role')==='tab')el.click();el?.scrollIntoView({block:'center',behavior:'smooth'});}});doSearch();
  const footerCols=[links.Research[0],links.Research[1],links.Research[2],links.Products[0],['API Platform','Overview|https://openai.com/api/','API Log In|https://platform.openai.com/login','Docs|https://developers.openai.com/api/docs'],links.Business[0],links.Developers[0],links.Company[0],['Support','Help Center|https://help.openai.com/'],['More','Stories|https://openai.com/stories/','Academy|https://academy.openai.com/','Supply Co.|https://supply.openai.com/','Podcast|https://openai.com/podcast/','RSS|https://openai.com/news/rss.xml'],['Terms & Policies','Terms of Use|https://openai.com/policies/terms-of-use/','Privacy Policy|https://openai.com/policies/privacy-policy/','Other Policies|https://openai.com/policies/']];
  document.getElementById('footer').innerHTML=`<div class="footer-grid">${Array.from({length:6},(_,i)=>`<div>${footerCols.filter((_,j)=>j%6===i).map(g=>`<div class="footer-group"><h3>${esc(g[0])}</h3>${g.slice(1).map(linkHTML).join('')}</div>`).join('')}</div>`).join('')}</div><div class="footer-bottom"><div class="socials">${['X|https://x.com/OpenAI','YouTube|https://youtube.com/OpenAI','LinkedIn|https://linkedin.com/company/openai','GitHub|https://github.com/openai','Instagram|https://instagram.com/openai'].map(linkHTML).join('')}</div><span>OpenAI © 2015–2026</span><a href="https://openai.com/policies/privacy-policy/" target="_blank" rel="noopener">Your privacy choices</a><a href="https://openai.com/" target="_blank" rel="noopener">◎ English · United States</a></div>`;
  document.addEventListener('click',e=>{const button=e.target.closest('[data-zoom]');if(button){const d=document.getElementById('image-dialog'),img=d.querySelector('img');img.src=button.dataset.zoom;img.alt=button.querySelector('img')?.alt||'Expanded image';d.showModal();}});
})();
